### ISSUE TITLE
Exception: Syntax error

### ISSUE THREAD

**Issue by jasperDD** [vavrecan/usb-boot-watcher#1]
Hi, why occurs this error
i run cmd as admin
C:\Intel>usbbootwatcher.exe /prepare j:\windows\system32
Copy from C:\Intel\UsbBootWatcher.exe
To j:\windows\system32\UsbBootWatcher.exe

Copy from UsbBootWatcher.conf
To j:\windows\system32\UsbBootWatcher.conf

Copy from j:\windows\system32\config\system
To j:\windows\system32\config\system.backup20190514183104

Registry hive loaded HKLM\USBBOOT
Target control set ControlSet002
Exception: Syntax error

C:\Intel>

**Comment by vavrecan** [comment]
UsbBootWatcher.conf is probably missing (not located in same directory as UsbBootWatcher.exe) or has invalid syntax
